language: node_js
node_js:
- '0.12'
env:
  global:
  - DEPLOY_BRANCH=develop
  - secure: "ZSVxIDXLepiNNFRGjX5fGqF+mqQVORC5VThcHq8xDXfKtA4LA45LCF8qcYi0OyTNAm4uMFvLrqyPElFlNbjJJ4BzYKiNkYgTq8ywLNAUVw2V6+oNmSkXk4PvMUX0COQcpW8vhWn2wdPJswqigNWpL/iewa0yBAMJ8VwD4J1FKAfToT3/m+gXuISfULeZVsZbPGor79DVLbfYkUteWfUQaRMbIWWWnO6OeYWOMzkE+Gxnar3BW8jQiD2nX62CIYlWJXrcYbQYCO/VRQgCV+61Ps+faisY7SmFMZmOZQYTO29A9dYVmPl3h4vHL2O7dKYAQXg7KXifczyi/UKgrCqtHmVJnrnPjUSMtSatGFQ0eWcwnRFeSaRwFaRuBe/xmlDubu2KvrNa6w4KFGFZ24ARSXPeJbPWvTiwjIJWkhs1cMBjioJZCteM69QEZPrGo1SdzdNSBnD8jj4upZaHe2qZQPQvwb7XSa7bpQwsnNi/cF+0qEmQBB9M82vQ5wA1MqMDSze6/TjHAD1C4Wy2sPOiECqkzgQ1a1Iv9IHbwrmU5N5G4AJ3XZ3Li9ThVEkbjQYtgmle1GhwktUmfaukPQhFKAFaWi4d7F+rngqXB2u/O71c5FMYdxNnOsgb+XufN2sC2T720wRhcKYxor2HTYgHAkjbzoViGqfGbfCCsvy4aQc="
cache:
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
# - "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
after_success:
- "./.build_scripts/deploy.sh"


25c183575ed023caa3652c6d656925d62b3c06ad