language: node_js
node_js:
- '0.12'
env:
  global:
  - DEPLOY_BRANCH=develop
  - secure: "NypJRaKF6CBQHqBBaFfptHcAetujOyOxa9kY3mUAc2Uru+MjCPG17FTSkq4MZavA0vrcNZ+e3pONjLapbiF2KL3uHe8OXNQP7dz6XI1cMMdM6P0Ks25HexX1Qv4WfcSxJSY0RM1xncAwQrpUobPaxL7/DHLkrs5ICRSNChILMlte9Ynquwb1vnWrQW3XGQ099PyDTKfLjZ2aBZJM8ZTpWAJyW//+R/H/duXy5QOfnCAnBe/OaFnGf7yOmi9LSfcHn3drsCLo04gK+bpljul2fBpCkg+L98cPONgD3FAP+JfhaFvTwAdeXSZVCubql9qUcr1F5KtJhVqM8wXTrnwNe2fttkHvLOI2mp+jq6uvzkTk7BebfJR31Tvag08oaol1hwwErxSkvjO3ywMbW8o+Mm+rfTCTSqC6dIBYDIPbEjcczTt8LWJyOeGcgftAHtB+H8vwf+C5iEkkBYmmeU5Z+otKH9rLfk4zeSFAcZP75GhL+TUCycRMkdWcTG7f+R/f8rjvt9fr2dvSKk5YHWMG+oKMfX7mVf/qbpXL7YD7rsJ19WnVd8cTK2dsVKNkV/KLdsDzU5oy3mE0c7IOgwuRmFp00CH/2YXz9jVVsLHzGzO8lJ4HmErGnqGDZoiwh5yn79MEAV4IrJBzBmYu93PPuc2ItJkg2oFBpVZGjXXWn1s="
cache:
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
# - "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
after_success:
- "./.build_scripts/deploy.sh"
