# Site settings
title: Daily Cardinal 125
safe:           false
source:         app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md
timezone: America/New_York
highlighter: false 

baseurl: "/DC125"

# dailycardinalalumni.github.io/DC125

##
# Collections definitions
##

collections:
  events:
    output: true
    permalink: /agenda/:slug/
  speakers:
    output: true
    permalink: /speakers/:path/
  sponsors:
    output: false
